version: 2.1

executors:
  mainexecutor:
    docker:
      - image: pkarnakov/aphros-gcc-openmp:0.1

jobs:
  build:
    executor: mainexecutor
    working_directory: ~/aphros
    steps:
      - restore_cache:
          keys:
            - cache-git-{{ .Environment.CacheSuff }}
      - checkout
      - save_cache:
          key: cache-git-{{ .Environment.CacheSuff }}
          paths:
            - .git

      - restore_cache:
          keys:
            - cache-deploy-{{ .Environment.CacheSuff }}
      - run:
          name: Build dependencies
          command: |
            cd deploy
            ./install_setenv -f ~/opt/aphros
            . ~/.local/bin/ap.setenv
            (mkdir -p build && cd build && cmake .. && make -j4 VERBOSE=1 && make install)
            cd ..
      - save_cache:
          key: cache-deploy-{{ .Environment.CacheSuff }}
          paths:
            - ~/aphros/deploy/build
            - ~/opt/aphros

      - run:
          command: |
            ls -al -R ~/opt/aphros || true
            ls -al -R ~/.local || true
            ls -al -R ~/aphros/deploy/build || true

      - restore_cache:
          keys:
            - cache-src-{{ .Environment.CacheSuff }}
      - run:
          name: Build source
          command: (. ~/.local/bin/ap.setenv && cd src && make -j4)
      - save_cache:
          key: cache-src-{{ .Environment.CacheSuff }}
          paths:
            - ~/aphros/src/build
            - ~/aphros/src/test

      - persist_to_workspace:
          root: ~/
          paths:
            - aphros
            - .local
            - opt

  test:
    executor: mainexecutor
    working_directory: ~/aphros
    steps:
      - run:
          name: Allow mpirun as root
          command: |
            mkdir -p \$HOME/.local/bin
            export PATH=\$HOME/.local/bin:\$PATH
            echo '/usr/bin/mpirun --allow-run-as-root "$@"' > \$HOME/.local/bin/mpirun
      - attach_workspace:
          at: ~/
      - run:
          name: Test
          command: (. ~/.local/bin/ap.setenv && cd src/build && ctest -j 4 --all)
      - store_artifacts:
          path: /root/aphros/src/build/Testing/Temporary/LastTest.log
          destination: LastTest.log

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
