version: 2.1

executors:
  mainexecutor:
    docker:
      - image: pkarnakov/aphros-gcc-openmp:0.1

# using environment variable CacheSuff
# defined in the Project Settings

jobs:
  build:
    executor: mainexecutor
    working_directory: ~/aphros
    steps:
      - restore_cache:
          keys:
            - cache-build-{{ .Environment.CacheSuff }}
      - checkout
      - run:
          name: Build dependencies
          command: |
            cd deploy
            ./install_setenv -f ~/opt/aphros
            . ~/.local/bin/ap.setenv
            mkdir -p build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j4
            make install
            cd ../..
      - run:
          name: Build source
          command: |
            . ~/.local/bin/ap.setenv
            mkdir -p src/build
            cd src/build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j4
            make install
            cd ../..
      - save_cache:
          key: cache-build-{{ .Environment.CacheSuff }}
          paths:
            - .git
            - ~/aphros
            - ~/opt/aphros

      - persist_to_workspace:
          root: ~/
          paths:
            - aphros
            - .local
            - opt

  test:
    executor: mainexecutor
    working_directory: ~/aphros
    environment:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test
          command: |
            . ~/.local/bin/ap.setenv
            cd src/build
            ctest -N | cut -d: -f 2 | head -n -2 | tail -n +2 | tr -d '\n' | cut -c 2- > list
            ctest -j 4 -R "$(circleci tests split list | tr ' ' '|')"
      - store_artifacts:
          path: /root/aphros/src/build/Testing/Temporary/LastTest.log
          destination: LastTest.log

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
