version: 2.1

executors:
  mainexecutor:
    docker:
      - image: gcc:latest

jobs:
  build:
    executor: mainexecutor
    working_directory: ~/aphros
    steps:
      - run:
          name: Install system packages
          command: |
            update-alternatives --install /usr/bin/gfortran gfortran /usr/local/bin/gfortran 999
            apt update
            apt install -y --no-install-recommends apt-utils
            apt install -y make cmake libhdf5-openmpi-dev hdf5-tools python3 python3-numpy sudo rsync libgsl-dev
            apt remove -y gfortran

      - restore_cache:
          keys:
            - cache-git
      - checkout
      - save_cache:
          key: cache-git
          paths:
            - .git

      - restore_cache:
          keys:
            - cache-deploy-v2
      - run:
          name: Build dependencies
          command: |
            cd deploy
            ./install_setenv -f ~/opt/aphros
            . ~/.local/bin/ap.setenv
            (mkdir -p build && cd build && cmake .. && make -j4 VERBOSE=1 && make install)
            cd ..
      - save_cache:
          key: cache-deploy-v2
          paths:
            - ~/aphros/deploy/build
            - ~/opt/aphros

      - run:
          command: |
            ls -al -R ~/opt/aphros || true
            ls -al -R ~/.local || true
            ls -al -R ~/aphros/deploy/build || true

      - restore_cache:
          keys:
            - cache-src
      - run:
          name: Build source
          command: (. ~/.local/bin/ap.setenv && cd src && make -j4)
      - save_cache:
          key: cache-src
          paths:
            - ~/aphros/src/build
            - ~/aphros/src/test

      - persist_to_workspace:
          root: ~/
          paths:
            - aphros
            - .local
            - opt

  test:
    executor: mainexecutor
    working_directory: ~/aphros
    steps:
      - run:
          name: Install system packages
          command: |
            update-alternatives --install /usr/bin/gfortran gfortran /usr/local/bin/gfortran 999
            apt update
            apt install -y --no-install-recommends apt-utils
            apt install -y make cmake libhdf5-openmpi-dev hdf5-tools python3 python3-numpy sudo rsync libgsl-dev
            apt remove -y gfortran
            mkdir -p \$HOME/.local/bin
            export PATH=\$HOME/.local/bin:\$PATH
            echo '/usr/bin/mpirun --allow-run-as-root "$@"' > \$HOME/.local/bin/mpirun
      - attach_workspace:
          at: ~/
      - run:
          name: Test
          command: (. ~/.local/bin/ap.setenv && cd src/build && ctest -j 4 --all)
      - store_artifacts:
          path: /root/aphros/src/build/Testing/Temporary/LastTest.log
          destination: LastTest.log

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
